apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      tolerations:
        - key: "node.role.kubernetes.io/control-plane"
          operator: "Exists"
          effects: "NoSchedule"
      containers:
        - name: web-ui
          image: ggmilesi/open-webui:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
