apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80           # Porta que o service expõe internamente (para os pods)
      targetPort: 80     # Porta do container que está sendo acessada
      nodePort: 30080    # Porta do node para acessar externamente o service
