apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard  # Substitua pelo StorageClass disponível no seu cluster
  #volumeName: postgres-pv  # Nome do PV específico a ser vinculado (opcional)
